name: Apply Terraform and Set Variables/Secrets

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Apply Infrastructure
    runs-on: ubuntu-latest
    outputs:
      instance_ip: ${{ steps.apply.outputs.instance_public_ip }}
      role_arn: ${{ steps.apply.outputs.role_arn }}
      ecr_repo_url: ${{ steps.apply.outputs.ecr_repository_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/terraform-github-actions@v2
        with:
          terraform_version: ">= 1.0.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Change to Terraform directory
        run: cd api/terraform

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color

  set_variables_secrets:
    name: Set Repository Variables and Secrets
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Login to GitHub CLI
        run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}

      - name: Set AWS_GITHUB_ACTIONS_ROLE_ARN variable
        run: gh variable set AWS_GITHUB_ACTIONS_ROLE_ARN "${{ needs.terraform.outputs.role_arn }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set ECR_REPOSITORY_NAME variable
        run: |
          REPO_URL="${{ needs.terraform.outputs.ecr_repo_url }}"
          REPO_NAME=$(echo "$REPO_URL" | sed 's#^[^/]\+/[^/]\+\/\([^/]\+\)$#\1#')
          gh variable set ECR_REPOSITORY_NAME "$REPO_NAME"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set EC2_INSTANCE_PUBLIC_IP variable
        run: gh variable set EC2_INSTANCE_PUBLIC_IP "${{ needs.terraform.outputs.instance_ip }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set HOST secret
        run: |
          if ${{ needs.terraform.outputs.instance_ip != '' }}; then
            gh secret set HOST -b "${{ needs.terraform.outputs.instance_ip }}"
            echo "HOST secret updated."
          else
            echo "EC2 instance IP address is not available, skipping HOST secret update."
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}